# .github/workflows/daily-linkedin-post.yml
name: Daily LinkedIn Post Generator

on:
  schedule:
    # Runs at 8:00 AM UTC every day (adjust timezone as needed)
    - cron: '0 8 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  generate-post:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install openai
    
    - name: Generate LinkedIn Post
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python linkedin_bot_github.py
    
    - name: Commit and push post history
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add linkedin_posts/
        git commit -m "Add daily LinkedIN post $(date)" || exit 0
        git push
