# .github/workflows/daily-linkedin-post.yml
name: Daily LinkedIn Post Generator

on:
  schedule:
    # Runs at 1:00 PM Australian Western Standard Time (Perth)
    # This is 5:00 AM UTC
    - cron: '0 5 * * *'
  workflow_dispatch: # Allows manual trigger

# Add permissions for the bot to push
permissions:
  contents: write

jobs:
  generate-post:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install openai
    
    - name: Generate LinkedIn Post
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python linkedin_bot_github.py
    
    - name: Commit and push post history
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add linkedin_posts/
        git commit -m "Add daily LinkedIn post $(date)" || exit 0
        git push